### ISSUE TITLE
Display BYE headers in the PCAP

### ISSUE THREAD

**Issue by Catharsis68** [jambonz/jambonz-feature-server#611]
## Feature Request

With PR #583 the `headers` of a hangup verb are now sent with the BYE
```yaml
# drachtio logs
BYE sip:3.72.114.185:5060 SIP/2.0
Via: SIP/2.0/UDP 10.1.203.102;rport;branch=z9hG4bK8a3HpZ25yvUmp
Max-Forwards: 70
From: <sip:+441409335812@3.72.114.185>;tag=g8XHeUZX98NBj
To: <sip:+14054321392@3.72.114.185:5060>;tag=428XtUU63QHmH
Call-ID: c1ba9122-2e3d-123d-e086-061fd753f9ff
CSeq: 78105630 BYE
Content-Length: 0
X-Reason: maximum call duration exceeded  <=
```

But the same call in Webapp > Recent Calls has a different **Call-ID** and in the PCAP BYE there are **no headers**
So I'm not able to find the call-id in the recent calls where the "x-reason" was set.

Could you please test this case as well?
